on: [push]

jobs:
  auth:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate API
        run: |
          curl -H "Authorization: Bearer $API_KEY" $API_URL
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_URL: ${{ secrets.API_URL }}

      - name: Run App
        run: node app.js
        env:
          API_KEY: ${{ secrets.API_KEY }}