name: Example Workflow

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Use secret
        run: echo "Secret is $API_KEY"
        env:
          MY_SECRET_KEY: ${{ secrets.API_KEY }}
