name: Run Node App

on: [push]

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Node app
        run: node app.js
        env:
          API_KEY: ${{ secrets.API_KEY }}